### ISSUE TITLE
Router and models?

### ISSUE THREAD

**Issue by thetechnaddict** [Pajn/falcor_dart#10]
Netflix describe falcor as a library for efficient data fetching - which includes falcon-router. 

Does this package port to dart the one model everywhere concept, enabling us to work with all the backend data as a JSON graph, or is it simply a router?

Please forgive the naive question!

**Comment by Pajn** [comment]
This project does currently only have the router, no models. We only use Dart on the server side so on the client we have Netflixs falcor package.

Currently there are no plans on adding the models so that would need someone else to step up.

**Comment by thetechnaddict** [comment]
Thanks for the clear response
